services:
  mysql:
    image: mysql:8.0
    container_name: agendaDatabase
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pw123az987"
      MYSQL_DATABASE: agenda
      MYSQL_USER: devs
      MYSQL_PASSWORD: "pw1234"
    network_mode: "host"
    volumes:
        - mysql_data:/var/lib/mysql
        - ./build/mysql/structure.sql:/docker-entrypoint-initdb.d/structure.sql:ro
volumes:
    mysql_data:
