services:
  mysql-test:
    image: mysql:8.0
    container_name: agendaDatabaseTest
    environment:
      MYSQL_ROOT_PASSWORD: "pw123az987"
      MYSQL_DATABASE: agenda_test
      MYSQL_USER: devs
      MYSQL_PASSWORD: "pw1234"
    ports:
      - "3308:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
      - ./src/main/java/infrastructure/sql/structure.sql:/docker-entrypoint-initdb.d/structure.sql:ro

volumes:
  mysql_test_data:
